
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=shp_supply;CharacterSet=UTF-8;TrustServerCertificate=True
    username: sa
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka
